language: generic
sudo: required

services:
    - docker
    
before_install:
    - docker build -t shantanumakkar/fibonacci-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true shantanumakkar/fibonacci-test npm run test

after_success:
    - docker build -t shantanumakkar/fibonacci-client ./client
    - docker build -t shantanumakkar/fibonacci-nginx ./nginx
    - docker build -t shantanumakkar/fibonacci-server ./server
    - docker build -t shantanumakkar/fibonacci-worker ./worker

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    - docker push shantanumakkar/fibonacci-client
    - docker push shantanumakkar/fibonacci-nginx
    - docker push shantanumakkar/fibonacci-server
    - docker push shantanumakkar/fibonacci-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-west-1-306476627547
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY